apiVersion: v1
kind: Service
metadata:
  name: {{ include "erebor.fullname" . }}
  labels:
    {{- include "erebor.labels" . | nindent 4 }}
  {{- with .Values.erebor.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.erebor.service.type }}
  ports:
    - port: {{ .Values.erebor.service.port }}
      targetPort: {{ .Values.erebor.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.erebor.app.metrics.enabled }}
    - port: {{ .Values.erebor.app.metrics.port }}
      targetPort: {{ .Values.erebor.app.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "erebor.selectorLabels" . | nindent 4 }}